name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          bump-minor-pre-major: true
          token: ${{ secrets.GITHUB_TOKEN }}
